service: heart-disease-prediction

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  deploymentBucket:
    name: heart-disease-data-prediction

functions:
  predict:
    handler: functions/predict.handler
    events:
      - http:
          path: predict
          method: post
    layers:
      - {Ref: NumpyLayer}
      - {Ref: PandasLayer}
      - {Ref: ScikitLearnLayer}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements_clean.txt
    dockerizePip: false  # Disable Docker usage
    slim: true  # Reduce package size by excluding unnecessary files
    zip: true  # Compress the package


package:
  exclude:
    - .gitignore
    - .git/**
    - tests/**
    - docs/**
    - '*.pyc'
    - '__pycache__/**'
    - node_modules/**
    - package.json
    - package-lock.json

resources:
  Resources:
    NumpyLayer:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: numpy-layer
        Content: { S3Bucket: your-s3-bucket-name, S3Key: path/to/numpy.zip }
        CompatibleRuntimes:
          - python3.8
    PandasLayer:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: pandas-layer
        Content: { S3Bucket: your-s3-bucket-name, S3Key: path/to/pandas.zip }
        CompatibleRuntimes:
          - python3.8
    ScikitLearnLayer:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: scikit-learn-layer
        Content: { S3Bucket: your-s3-bucket-name, S3Key: path/to/scikit-learn.zip }
        CompatibleRuntimes:
          - python3.8
