service: heart-disease-prediction

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: heart-disease-data-prediction
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: arn:aws:s3:::heart-disease-data-prediction/*

functions:
  predict:
    handler: functions/predict.handler
    layers:
      - arn:aws:lambda:us-east-1:533267181604:layer:pandas_boto3:1
      - arn:aws:lambda:us-east-1:533267181604:layer:joblib_sklearn:1
    events:
      - http:
          path: predict
          method: post
          cors: true
  train_models:
    handler: functions/training.handler
    layers:
      - arn:aws:lambda:us-east-1:533267181604:layer:pandas_boto3:1
      - arn:aws:lambda:us-east-1:533267181604:layer:joblib_sklearn:1

plugins:
  - serverless-python-requirements
  - serverless-layers

custom:
  pythonRequirements:
    dockerizePip: false  # Disable Docker
    layer: true
  serverless-layers:
    layersDeploymentBucket: heart-disease-data-prediction

package:
  patterns:
    - '!node_modules/**'
    - '!__pycache__/**'
    - '!tests/**'
    - '!docs/**'
    - '!functions/processing.py'
    - '!functions/training.py'
    - '!Dockerfile'
    - '!package.json'
    - '!package-lock.json'
    - '!six.py'
    - '!threadpoolctl.py'
    - '!catboost_info'
    - '!requirements.txt'
